---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: system-entry
spec:
 hosts:
   - system-provider.threescale.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
   - name: http
     number: 80
     protocol: HTTP
 resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: backend-entry
spec:
 hosts:
  - backend-listener.threescale.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
  - name: http
    number: 80
    protocol: HTTP
 resolution: DNS
