kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kafka-servicemesh
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.3'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka-servicemesh
  name: scores
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: scores
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka-servicemesh
  name: object-scores
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: object-scores
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka-servicemesh
  name: scores-aggregated
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: scores-aggregated